version: '3.7'
services:
    php:
        build:
            context: ./docker/php
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - .:/var/www/sellermania-pricing:delegated
        depends_on:
            - db

    nginx:
        image: nginx:1.19.0
        user: "${UID}:${GID}"
        ports:
            - 8000:80
        volumes:
            - .:/var/www/sellermania-pricing:delegated
            - ./docker/nginx/conf.d/www.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        environment:
            TIMEZONE: Europe/Paris

    db:
        # This image exposes the standard MySQL port (3306)
        image: mysql:8.0
        command: ['mysqld','--character-set-server=utf8','--default-authentication-plugin=mysql_native_password']
        ports:
            - 3307:3306
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        restart: on-failure

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        depends_on:
            - db
        links:
            - db
        # phpmyadmin port defined to 3002
        ports:
            - "3308:80"
        restart: on-failure
        environment:
            PMA_HOST: ${PMA_HOST}
            PMA_USER: ${PMA_USER}
            PMA_PASSWORD: ${PMA_PASSWORD}

volumes:
    db-data: {}